name: Update Profile README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public profile repo
        uses: actions/checkout@v3

      - name: Fetch README from private repo
        run: |
          curl -H "Authorization: token ${{ secrets.README_TOKEN }}" -o README.md https://raw.githubusercontent.com/reshmaoleti/profile-readme/main/README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README" || exit 0
          git push --quiet
